version: '3'
services:
  xkcd-jupiterhub:
    build: .
    ports:
     - "127.0.0.1:8888:8888"
    volumes:
     - ./work:/home/jovyan/work
     - .aws/credentials:/home/jovyan/.aws/credentials
    environment:
      - JUPYTER_ENABLE_LAB=true
      - JUPYTER_TOKEN=xkcd
